version: '3.8'

services:
  bot:
    build: .
    container_name: survey-bot

    env_file: .env

    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod} # по умолчанию prod, для dev: SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./reports:/app/reports
    depends_on:
      - db
    restart: always
    networks:
      - survey-net

  db:
    image: postgres:15
    container_name: surveybot-db

    env_file: .env

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - survey-net

volumes:
  pgdata:

networks:
  survey-net: