version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-survey-bot
    environment:
      - DB_URL=jdbc:postgresql://db:5432/surveybot
      - DB_USER=surveyuser
      - DB_PASSWORD=surveypass
    volumes:
      - ./reports:/app/reports
    depends_on:
      - db
    restart: always
    networks:
      - survey-net

  db:
    image: postgres:15
    container_name: surveybot-db
    environment:
      - POSTGRES_DB=surveybot
      - POSTGRES_USER=surveyuser
      - POSTGRES_PASSWORD=surveypass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - survey-net

volumes:
  pgdata:

networks:
  survey-net: