version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-survey-bot
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - TELEGRAM_BOT_TOKEN=7699108540:AAGK_HQugzmYct5JZua2gp_dXsJsMojLWKQ
      - TELEGRAM_BOT_USERNAME=my_surveybot_bot
    volumes:
      - ./reports:/app/reports
    depends_on:
      - db
    restart: always
    networks:
      - survey-net

  db:
    image: postgres:15
    container_name: surveybot-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - survey-net

volumes:
  pgdata:

networks:
  survey-net: